### ISSUE TITLE
Use GitHub Pages to Host myUAH-2.0

### ISSUE THREAD

**Issue by wsciaroni** [Republik631/myUAH-2.0#4]
I think it would be advantageous to have this hosted on GitHub Pages.  It's a simple 4 click process if you'd like.

1. Settings
2. Options->GitHub Pages
3. Set Branch to `official_edits` or whatever branch you want hosted as the release.
4. Make sure root is selected. Then click save

Thoughts?

**Comment by Republik631** [comment]
Hi Will!

That's a interesting idea. Currently I host from the server in SSB, and a very generous OIT staff member has set up myUAH 2 with a uah.edu subdomain. I don't want to lose that subdomain by hosting from Github. 

Do you know if there is some sort of forwarding I could put in the htaccess file on the current hosting server to redirect to Github Pages, so that going to alt.uah.edu would still work?

I'm interested in your suggestion but I don't want to mess with how the site is currently accessed.

**Comment by wsciaroni** [comment]
@Republik631 Ah, I didn't know it was being hosted elsewhere.

If you're interested in having it auto-deployed to your current server, you could certainly do that.  I wouldn't host it with GHPages since you've already got it hosted elsewhere.

**Comment by Republik631** [comment]
I'll look into auto deploying it from Github. Currently I edit the files straight from server, but I'd like to have the github always match the live site. Thanks for that suggestion!

**Comment by wsciaroni** [comment]
Awesome!
Do you think you could throw a link to the site in the README for those who stumble on this repo?

**Comment by Republik631** [comment]
I can! I honestly didn't think anyone would find this except from the link on the site itself.

**Comment by wsciaroni** [comment]
I was searching for a bot that would click through the healthcheck for me... In searching I ended up landing on this Repo.

Very good. I'll mark this as closed since it sounds like you've got a plan.
